name: fluttercraft
description: Cross-platform Flutter build CLI - Craft Your Flutter Builds with Precision.
version: 0.2.14
repository: https://github.com/venhdev/fluttercraft-cli.git
homepage: https://github.com/venhdev/fluttercraft-cli
issue_tracker: https://github.com/venhdev/fluttercraft-cli/issues

environment:
  sdk: ^3.4.0

executables:
  flc: fluttercraft
  fluttercraft: fluttercraft

dependencies:
  # Command-line argument parsing
  args: ^2.7.0
  
  # YAML parsing for pubspec.yaml
  yaml: ^3.1.3
  
  # Cross-platform path utilities
  path: ^1.9.1

  # Color support
  colored_logger: ^2.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.28.0
